### ISSUE TITLE
Add support for video/quicktime file transformation

### ISSUE THREAD

**Issue by rob93c** [Stickerifier/Stickerify#10]
The bot should be able to successfully process a file with MIME type video/quicktime (which represents GIFs in Telegram) and return the resized [.webm](https://core.telegram.org/stickers/webm-vp9-encoding)

**Comment by mindfreakersatya** [comment]
So for gif file with image/gif mime type would work if we remove .gif extension from unsupported array but then for gif file with video/<Type> we should do some other task

**Comment by anthonylgf** [comment]
Hello @rob93c, I would like to work on that issue, can you assignee it to me?

**Comment by rob93c** [comment]
Hi @anthonylgf, thank you for your interest in this issue!
Be sure to check how Telegram handles video stickers: https://core.telegram.org/stickers#video-stickers-and-emoji

**Comment by anthonylgf** [comment]
I checked and I found that Java apparently does not convert .gif(v) files to .webm. I will need to use the [ffmpeg](https://ffmpeg.org/) and use JNI to call the C library.

**Comment by anthonylouisbsb** [comment]
I found a dependency that is an wrapper for the ffmpeg, I will use it https://github.com/a-schild/jave2

**Comment by rob93c** [comment]
Nice find @anthonylgf!
If you think it could be useful, we might create a new helper class with the logic you are adding called `VideoHelper` renaming the [`image package`](https://github.com/rob93c/Stickerify/tree/main/src/main/java/com/cellar/stickerify/image) to `media`

Also, don't worry about unit testing your changes for the time being (of course if you want to add them you are more than welcomed)

**Comment by rob93c** [comment]
Hi @anthonylgf (@anthonylouisbsb?), how is it going? Do you need any help with this issue?

**Comment by rob93c** [comment]
Hello @anthonylgf, please share any update or I will need to reassign the issue to someone else as per [our latest discussion](https://github.com/Stickerifier/Stickerify/discussions/39).
