### ISSUE TITLE
Send usage message when a user starts the bot

### ISSUE THREAD

**Issue by rob93c** [Stickerifier/Stickerify#154]
When a new user activates the bot (sending the `/start` command), it should be prompted with [the message explaining how the bot works](https://github.com/Stickerifier/Stickerify/blob/main/src/main/java/com/github/stickerifier/stickerify/telegram/Answer.java#L8-L16) but the current implementation shows [the about message](https://github.com/Stickerifier/Stickerify/blob/main/src/main/java/com/github/stickerifier/stickerify/telegram/Answer.java#L28-L32).

To be done:
- [ ] fix the implementation of [`getAnswerMessage()`](https://github.com/Stickerifier/Stickerify/blob/main/src/main/java/com/github/stickerifier/stickerify/telegram/model/TelegramRequest.java#L80-L82) to handle the start command
- [ ] if a new method is needed to check if the message represents the start command, consider using it also in [`getDescription()`](https://github.com/Stickerifier/Stickerify/blob/main/src/main/java/com/github/stickerifier/stickerify/telegram/model/TelegramRequest.java#L77)
- [ ] check unit tests in `StickerifyTest`: if they still work after the change, add a test to verify this scenario
- [ ] update [the flowchart in the readme](https://github.com/Stickerifier/Stickerify/blob/main/README.md?plain=1#L38) to mention that also the start command triggers the usage message

**Comment by rob93c** [comment]
Hey @marcofranzoni, would you like to work on this issue?

**Comment by ritikverma2000** [comment]
Hi @rob93c can I work on this issue as well if @marcofranzoni is not currently working on it ?

**Comment by rob93c** [comment]
Hi @ritikverma2000! Since there's no rush in completing this ticket I'd leave it for @marcofranzoni to work on

**Comment by ritikverma2000** [comment]
@rob93c can you assign me some new issue then to work upon ?

**Comment by rob93c** [comment]
Hi @ritikverma2000, currently there are no available issues to be worked on; I'd recommend you to use the bot, try to find bugs or suggest improvements: you may then create an issue so we can discuss and analyze them.

Since this isn't the correct place to have this sort of discussion (as this isn't related to the issue you are commenting on), please consider reading our [contributing guidelines](https://github.com/Stickerifier/Stickerify/blob/main/CONTRIBUTING.md) and [open a discussion](https://github.com/orgs/Stickerifier/discussions/new/choose) if you need further clarifications.
