### ISSUE TITLE
Animated stickers running at 30FPS don't pass validation

### ISSUE THREAD

**Issue by rob93c** [Stickerifier/Stickerify#161]
Despite [Telegram's requirements for animated stickers](https://core.telegram.org/stickers#animation-requirements) stating that  _All animations must run at 60 Frames Per Second_, 30 FPS animations are still allowed: for instance the pack [SteampunkJulia](https://t.me/addstickers/SteampunkJulia) contains such stickers.

[Bot's animated sticker validation](https://github.com/Stickerifier/Stickerify/blob/main/src/main/java/com/github/stickerifier/stickerify/media/MediaHelper.java#L151-L155) should be amended to check that the FPS are **at most** 60.

Also, add a unit test checking that a low FPS animated sticker passes the validation, similarly to the existing [`noAnimatedStickerConversionNeeded()`](https://github.com/Stickerifier/Stickerify/blob/main/src/test/java/com/github/stickerifier/stickerify/media/MediaHelperTest.java#L176-L182).

In the meanwhile, the bug has been reported to Telegram: https://bugs.telegram.org/c/33112

**Comment by ritikverma2000** [comment]
Hi @rob93c I would like to work on this issue I have raised this PR can you have a look once.  
https://github.com/Stickerifier/Stickerify/pull/164

**Comment by rob93c** [comment]
Hi @ritikverma2000 and thank you for working on this issue! 
I'll assign it to you and I'll review your changes as soon as possible

**Comment by ritikverma2000** [comment]
Hi @rob93c I had one concern regarding the test case, how would we be getting the FPS inside the test case for an animated sticker?
![image](https://github.com/Stickerifier/Stickerify/assets/42388388/c36cdf3b-a166-4e6b-9196-671e9292dede)

**Comment by rob93c** [comment]
I think we should approach this test from a different perspective: we know that an animated sticker running at 30FPS would make the conversion fail (prior to your changes) so we can add a sticker with those characteristics to the folder [`test/resources/`](https://github.com/Stickerifier/Stickerify/tree/main/src/test/resources).
We now have a file we can use to test if the changes you made are correct, you can create a test to check that the conversion of such file is now successful (in this case, the success means that `null` is returned as in the previous test).

As to where to find such file to use in the test, you can open the sticker pack [SteampunkJulia](https://t.me/addstickers/SteampunkJulia) and download one of them; maybe a good name for that file would be `low_fps_animated_sticker.tgs`

Feel free to ping me if you have any doubt

**Comment by ritikverma2000** [comment]
Ya, that approach seems correct to me @rob93c . Added the code for the test case pls check this, 
PR again --> https://github.com/Stickerifier/Stickerify/pull/164

**Comment by ritikverma2000** [comment]
Hi @rob93c can you pls check as to why this is failing 
![image](https://github.com/Stickerifier/Stickerify/assets/42388388/a67935b3-7540-4988-8613-d3ca54da165a)

**Comment by ritikverma2000** [comment]
Thanks @rob93c for guiding me.

**Comment by rob93c** [comment]
It was failing because Github workflows triggered by forks of a repo can't access the main repository's secrets, in this case the ones with the credentials used to access Docker but that's not an issue so I approved and merged the pull request 🔥 

I really appreciate your help, thank you for contributing to this project 😄
