### ISSUE TITLE
The bot doesn't validate produced file's size

### ISSUE THREAD

**Issue by quartzwine** [Stickerifier/Stickerify#222]
bot doesnt have hard limit on size of file outputted. image i provided gave me outputted image of 614 KB which is beyond 512KB limit size for stickers

**Comment by rob93c** [comment]
Hi @quartzwine and thanks for reporting this issue!
Would you like to work on this issue or should we tackle it?

On a side note, would you be able to share with us the image that highlighted this bug? Maybe we can use it in a new unit test

**Comment by quartzwine** [comment]
you guys can tackle it, i went an alternative route. attached image
![sampleimage](https://github.com/Stickerifier/Stickerify/assets/142696568/126dcba7-18fe-4532-9847-4885752508be)

**Comment by rob93c** [comment]
Thanks for the image, that will be very useful working on this bug 🐈‍⬛

**Comment by r0nz-29** [comment]
hey @rob93c
let me know if this is still open, I'd like to contribute

**Comment by rob93c** [comment]
Hi @r0nz-29! I already worked on the pull request and it's currently on code review -> #232 
Please, feel free to have a look at it and leave comments if you find anything to improve or if you have any question 😄
