### ISSUE TITLE
Answer with the error message when sending an audio to the bot

### ISSUE THREAD

**Issue by rob93c** [Stickerifier/Stickerify#42]
Currently, if you send a voice message to the bot, it will answer with its info message instead of the error (as it does when it receives an invalid file to convert):

![image](https://user-images.githubusercontent.com/1816483/199767516-7b6fcbf1-814f-4de2-b09b-2bb5261b213a.png)

Probably the issue is due to the current implementation of the method [`TelegramRequest.hasFile()`](https://github.com/Stickerifier/Stickerify/blob/main/src/main/java/com/github/stickerifier/stickerify/telegram/model/TelegramRequest.java#L23-L25):

````java
public boolean hasFile() {
    return message.hasPhoto() || message.hasDocument() || message.hasSticker() || message.hasVideo() || message.hasAudio();
}
````

**EDIT:** the same happens sending a video message to the bot, it should be handled as part of this ticket as well.

**Comment by rob93c** [comment]
Hi @marcofranzoni, would you like to look into this issue?

**Comment by marcofranzoni** [comment]
I couldn't say no to issue #42!

**Comment by rob93c** [comment]
Hi @marcofranzoni, do you have any update on this regard?
Let me know if I can help

**Comment by rob93c** [comment]
Hello @marcofranzoni!
Recently the project was upgraded to handle video conversion via FFmpeg (#68) and I think it would be great to allow video message conversion within this issue.

To wrap up, this requirements are:
1. sending a **voice message** to the bot should result in its **error** answer
2. sending a **video message** to the bot should result in a **successful conversion** of said video
